#
# Grader comments 2014.05.19
# Doesn't compile properly. With the necessary compiler flags turned
# on, it doesn't compile at all.
#
pc28: pc28.cpp item.h fooditem.h magicitem.h
	g++ -Wno-newline-eof -Wall -Werror -pedantic -Wextra -o ../exec/pc28 pc28.cpp
